import { 
  StudentProfile, 
  AttendanceRecord, 
  CorrectionRequest, 
  AuditLogRecord, 
  RFIDDevice, 
  ClassroomSession, 
  DayAttendanceCalendar 
} from '../types';

export const CURRENT_STUDENT: StudentProfile = {
  id: 'SEC24CSE1023',
  registerNumber: 'SEC24CSE1023',
  name: 'Arun Kumar',
  department: 'Computer Science & Engineering',
  semester: 'Semester 5 (Fall 2026)',
  section: 'Section B',
  email: 'arun.cse24@srmuniv.ac.in',
  rfidTagId: 'EPC: E280-1160-4492-7A01',
  monthlyAttendance: 91.6,
  totalClasses: 142,
  presentCount: 130,
  absentCount: 8,
  lateCount: 4,
  todayStatus: 'Present',
  todayEntry: '09:04 AM',
  todayExit: '10:52 AM',
  todayDuration: '1h 48m',
};

export const INITIAL_STUDENT_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-101',
    date: '2026-10-01',
    subject: 'Computer Networks',
    classroom: 'Room 204',
    entryTime: '09:02 AM',
    exitTime: '10:48 AM',
    duration: '1h 46m',
    status: 'Present',
    source: 'RFID Automatic',
  },
  {
    id: 'att-102',
    date: '2026-10-02',
    subject: 'Cyber Security',
    classroom: 'Room 305',
    entryTime: '09:11 AM',
    exitTime: '10:45 AM',
    duration: '1h 34m',
    status: 'Late',
    source: 'RFID Automatic',
    notes: 'Entered 11 mins past gate cutoff',
  },
  {
    id: 'att-103',
    date: '2026-09-30',
    subject: 'Database Management Systems',
    classroom: 'Lab 3',
    entryTime: '11:00 AM',
    exitTime: '12:50 PM',
    duration: '1h 50m',
    status: 'Present',
    source: 'RFID Automatic',
  },
  {
    id: 'att-104',
    date: '2026-09-29',
    subject: 'Operating Systems',
    classroom: 'Room 201',
    entryTime: '09:03 AM',
    exitTime: '10:40 AM',
    duration: '1h 37m',
    status: 'Present',
    source: 'RFID Automatic',
  },
  {
    id: 'att-105',
    date: '2026-09-28',
    subject: 'Design & Analysis of Algorithms',
    classroom: 'Room 204',
    entryTime: '--:--',
    exitTime: '--:--',
    duration: '0h 00m',
    status: 'Absent',
    source: 'RFID Automatic',
    notes: 'No UHF tag detected in portal',
  },
  {
    id: 'att-106',
    date: '2026-09-27',
    subject: 'Web Technologies Lab',
    classroom: 'Lab 2',
    entryTime: '02:02 PM',
    exitTime: '03:55 PM',
    duration: '1h 53m',
    status: 'Present',
    source: 'RFID Automatic',
  },
  {
    id: 'att-107',
    date: '2026-09-26',
    subject: 'Software Engineering',
    classroom: 'Room 108',
    entryTime: '10:04 AM',
    exitTime: '11:50 AM',
    duration: '1h 46m',
    status: 'Present',
    source: 'Manual Override',
    notes: 'Approved via Correction Req #CR-104 - RFID antenna glitch',
  },
  {
    id: 'att-108',
    date: '2026-09-25',
    subject: 'Computer Architecture',
    classroom: 'Room 204',
    entryTime: '09:14 AM',
    exitTime: '10:50 AM',
    duration: '1h 36m',
    status: 'Late',
    source: 'RFID Automatic',
  }
];

export const INITIAL_CALENDAR_DAYS: DayAttendanceCalendar[] = [
  { date: '2026-09-07', dayName: 'MON', dayNumber: 7, status: 'Present', subjectSummary: 'CN, DAA, DBMS' },
  { date: '2026-09-08', dayName: 'TUE', dayNumber: 8, status: 'Present', subjectSummary: 'OS, CyberSec, Math' },
  { date: '2026-09-09', dayName: 'WED', dayNumber: 9, status: 'Present', subjectSummary: 'CN, DBMS Lab' },
  { date: '2026-09-10', dayName: 'THU', dayNumber: 10, status: 'Late', subjectSummary: 'OS, DAA' },
  { date: '2026-09-11', dayName: 'FRI', dayNumber: 11, status: 'Present', subjectSummary: 'Web Tech, Project' },
  
  { date: '2026-09-14', dayName: 'MON', dayNumber: 14, status: 'Present', subjectSummary: 'CN, DAA, DBMS' },
  { date: '2026-09-15', dayName: 'TUE', dayNumber: 15, status: 'Holiday', subjectSummary: 'University Founders Day' },
  { date: '2026-09-16', dayName: 'WED', dayNumber: 16, status: 'Present', subjectSummary: 'CN, DBMS Lab' },
  { date: '2026-09-17', dayName: 'THU', dayNumber: 17, status: 'Present', subjectSummary: 'OS, DAA' },
  { date: '2026-09-18', dayName: 'FRI', dayNumber: 18, status: 'Absent', subjectSummary: 'Medical leave filed' },

  { date: '2026-09-21', dayName: 'MON', dayNumber: 21, status: 'Present', subjectSummary: 'CN, DAA, DBMS' },
  { date: '2026-09-22', dayName: 'TUE', dayNumber: 22, status: 'Present', subjectSummary: 'OS, CyberSec' },
  { date: '2026-09-23', dayName: 'WED', dayNumber: 23, status: 'Late', subjectSummary: 'CN, DBMS Lab' },
  { date: '2026-09-24', dayName: 'THU', dayNumber: 24, status: 'Present', subjectSummary: 'OS, DAA' },
  { date: '2026-09-25', dayName: 'FRI', dayNumber: 25, status: 'Late', subjectSummary: 'Web Tech' },

  { date: '2026-09-28', dayName: 'MON', dayNumber: 28, status: 'Absent', subjectSummary: 'Tag Not Detected' },
  { date: '2026-09-29', dayName: 'TUE', dayNumber: 29, status: 'Present', subjectSummary: 'OS, CyberSec' },
  { date: '2026-09-30', dayName: 'WED', dayNumber: 30, status: 'Present', subjectSummary: 'DBMS Lab' },
  { date: '2026-10-01', dayName: 'THU', dayNumber: 1, status: 'Present', subjectSummary: 'CN (Today)' },
  { date: '2026-10-02', dayName: 'FRI', dayNumber: 2, status: 'Late', subjectSummary: 'Cyber Security' }
];

export const INITIAL_CORRECTION_REQUESTS: CorrectionRequest[] = [
  {
    id: 'CR-101',
    studentName: 'Arun Kumar',
    studentId: 'SEC24CSE1023',
    date: '2026-09-28',
    subject: 'Design & Analysis of Algorithms',
    issueType: 'RFID not detected',
    description: 'I was seated in Room 204 on row 3 from 09:00 AM to 10:45 AM. The RFID doorway reader seems to have missed my card during the heavy crowd rush at 08:58 AM.',
    rfidLog: 'Reader 01: Tag E280-1160-4492 not captured in scan beam (Buffer overload flag 0x02)',
    currentAttendance: 'Absent',
    status: 'Pending',
    submittedAt: '2026-09-28 02:15 PM'
  },
  {
    id: 'CR-102',
    studentName: 'Priya Sharma',
    studentId: 'SEC24CSE1045',
    date: '2026-09-29',
    subject: 'Operating Systems',
    issueType: 'Incorrect exit time',
    description: 'Reader recorded my exit at 09:20 AM instead of 10:40 AM because I stepped to the doorway to submit a signed assignment sheet to the teaching assistant.',
    rfidLog: 'Reader 02: Exit trigger timestamp 09:20:14 AM RSSI -64dBm',
    currentAttendance: 'Absent',
    status: 'Under Review',
    submittedAt: '2026-09-29 11:30 AM'
  },
  {
    id: 'CR-103',
    studentName: 'Vikas Rao',
    studentId: 'SEC24CSE1089',
    date: '2026-09-27',
    subject: 'Computer Networks',
    issueType: 'Incorrect entry time',
    description: 'Walked in at 09:02 AM but registered at 09:18 AM when re-entering after picking up lab manual from locker.',
    rfidLog: 'Reader 01: Secondary tag capture at 09:18:02 AM RSSI -58dBm',
    currentAttendance: 'Late',
    status: 'Resolved',
    submittedAt: '2026-09-27 01:10 PM',
    adminReason: 'Verified classroom CCTV timestamp at 09:02 AM. Status updated to Present.',
    resolvedAt: '2026-09-27 04:30 PM',
    resolvedBy: 'admin_204 (Prof. K. Venkatesh)'
  },
  {
    id: 'CR-104',
    studentName: 'Arun Kumar',
    studentId: 'SEC24CSE1023',
    date: '2026-09-26',
    subject: 'Software Engineering',
    issueType: 'RFID not detected',
    description: 'RFID portal showed orange indicator light during entry. Attended entire 2 hour lecture.',
    rfidLog: 'Reader 04: Hardware sync glitch documented between 10:00 - 10:15 AM',
    currentAttendance: 'Present',
    status: 'Resolved',
    submittedAt: '2026-09-26 12:40 PM',
    adminReason: 'Known reader antenna sync outage during period 2. Manually validated against batch attendance roster.',
    resolvedAt: '2026-09-26 03:15 PM',
    resolvedBy: 'admin_204 (Prof. K. Venkatesh)'
  },
  {
    id: 'CR-105',
    studentName: 'Deepak Nambiar',
    studentId: 'SEC24CSE1112',
    date: '2026-09-25',
    subject: 'Computer Architecture',
    issueType: 'Other',
    description: 'Card was in backpack with metallic thermos bottle which blocked RF propagation.',
    rfidLog: 'Reader 01: Zero RSSI recorded during whole lecture block',
    currentAttendance: 'Absent',
    status: 'Rejected',
    submittedAt: '2026-09-25 04:00 PM',
    adminReason: 'Student confirmed absent by faculty roll check at 09:30 AM. No justification provided.',
    resolvedAt: '2026-09-26 09:00 AM',
    resolvedBy: 'admin_101 (Dean of Academics)'
  }
];

export const INITIAL_AUDIT_LOGS: AuditLogRecord[] = [
  {
    id: 'AUD-8821',
    adminId: 'admin_204',
    adminName: 'Prof. K. Venkatesh',
    studentId: 'SEC24CSE1023',
    studentName: 'Arun Kumar',
    date: '2026-10-01',
    subject: 'Computer Networks',
    classroom: 'Room 204',
    originalStatus: 'Absent',
    newStatus: 'Present',
    reason: 'RFID reader was offline during the first 20 minutes of the class.',
    timestamp: '01 Oct 2026, 10:32 AM',
    action: 'Manual Override'
  },
  {
    id: 'AUD-8819',
    adminId: 'admin_204',
    adminName: 'Prof. K. Venkatesh',
    studentId: 'SEC24CSE1089',
    studentName: 'Vikas Rao',
    date: '2026-09-27',
    subject: 'Computer Networks',
    classroom: 'Room 204',
    originalStatus: 'Late',
    newStatus: 'Present',
    reason: 'Correction Request #CR-103 approved: Doorway congestion delayed tag buffer transmission.',
    timestamp: '27 Sep 2026, 04:30 PM',
    action: 'Correction Approval'
  },
  {
    id: 'AUD-8814',
    adminId: 'admin_108',
    adminName: 'Dr. Meenakshi S.',
    studentId: 'SEC24CSE1042',
    studentName: 'Sneha Reddy',
    date: '2026-09-26',
    subject: 'Operating Systems',
    classroom: 'Room 201',
    originalStatus: 'Absent',
    newStatus: 'Present',
    reason: 'RFID card damaged. Temporary replacement tag assigned pending re-issuance.',
    timestamp: '26 Sep 2026, 11:15 AM',
    action: 'Manual Override'
  },
  {
    id: 'AUD-8802',
    adminId: 'admin_204',
    adminName: 'Prof. K. Venkatesh',
    studentId: 'SEC24CSE1023',
    studentName: 'Arun Kumar',
    date: '2026-09-26',
    subject: 'Software Engineering',
    classroom: 'Room 108',
    originalStatus: 'Absent',
    newStatus: 'Present',
    reason: 'Reader malfunction documented during period 2 doorway power surge.',
    timestamp: '26 Sep 2026, 03:15 PM',
    action: 'Correction Approval'
  },
  {
    id: 'AUD-8795',
    adminId: 'admin_101',
    adminName: 'Dr. R. Ramanathan',
    studentId: 'SEC24CSE1150',
    studentName: 'Aditya Nair',
    date: '2026-09-24',
    subject: 'Design & Analysis of Algorithms',
    classroom: 'Room 204',
    originalStatus: 'Late',
    newStatus: 'Present',
    reason: 'New student ID card was not registered in central EPC database until 11:00 AM.',
    timestamp: '24 Sep 2026, 02:45 PM',
    action: 'Manual Override'
  },
  {
    id: 'AUD-8780',
    adminId: 'admin_101',
    adminName: 'Dr. R. Ramanathan',
    studentId: 'SEC24CSE1018',
    studentName: 'Ananya Deshmukh',
    date: '2026-09-22',
    subject: 'Cyber Security',
    classroom: 'Room 305',
    originalStatus: 'Absent',
    newStatus: 'Present',
    reason: 'System synchronization failure between ESP32 gateway node and Firebase broker.',
    timestamp: '22 Sep 2026, 01:20 PM',
    action: 'Manual Override'
  }
];

export const INITIAL_RFID_DEVICES: RFIDDevice[] = [
  {
    id: 'DEV-01',
    name: 'Reader 01',
    classroom: 'Room 204',
    status: 'ONLINE',
    lastSync: '09:42 AM',
    antennaCount: 4,
    frequencyBand: '865.7 - 867.5 MHz (EPC Gen 2)',
    tagsDetectedToday: 384,
    signalStrength: 98,
    ipAddress: '192.168.10.41'
  },
  {
    id: 'DEV-02',
    name: 'Reader 02',
    classroom: 'Room 205',
    status: 'ONLINE',
    lastSync: '09:41 AM',
    antennaCount: 2,
    frequencyBand: '865.7 - 867.5 MHz (EPC Gen 2)',
    tagsDetectedToday: 219,
    signalStrength: 94,
    ipAddress: '192.168.10.42'
  },
  {
    id: 'DEV-03',
    name: 'Reader 03',
    classroom: 'Room 301',
    status: 'OFFLINE',
    lastSync: '08:17 AM',
    antennaCount: 4,
    frequencyBand: '865.7 - 867.5 MHz (EPC Gen 2)',
    tagsDetectedToday: 42,
    signalStrength: 0,
    ipAddress: '192.168.10.43'
  },
  {
    id: 'DEV-04',
    name: 'Reader 04',
    classroom: 'Central Library',
    status: 'ONLINE',
    lastSync: '09:42 AM',
    antennaCount: 4,
    frequencyBand: '865.7 - 867.5 MHz (EPC Gen 2)',
    tagsDetectedToday: 512,
    signalStrength: 99,
    ipAddress: '192.168.10.44'
  },
  {
    id: 'DEV-05',
    name: 'Reader 05',
    classroom: 'Seminar Hall A',
    status: 'ONLINE',
    lastSync: '09:40 AM',
    antennaCount: 6,
    frequencyBand: '865.7 - 867.5 MHz (EPC Gen 2)',
    tagsDetectedToday: 180,
    signalStrength: 92,
    ipAddress: '192.168.10.45'
  },
  {
    id: 'DEV-06',
    name: 'Reader 06',
    classroom: 'Physics Lab',
    status: 'WARNING',
    lastSync: '09:28 AM',
    antennaCount: 2,
    frequencyBand: '865.7 - 867.5 MHz (EPC Gen 2)',
    tagsDetectedToday: 96,
    signalStrength: 62,
    ipAddress: '192.168.10.46'
  },
  {
    id: 'DEV-07',
    name: 'Reader 07',
    classroom: 'Room 305',
    status: 'ONLINE',
    lastSync: '09:42 AM',
    antennaCount: 4,
    frequencyBand: '865.7 - 867.5 MHz (EPC Gen 2)',
    tagsDetectedToday: 290,
    signalStrength: 96,
    ipAddress: '192.168.10.47'
  },
  {
    id: 'DEV-08',
    name: 'Reader 08',
    classroom: 'Main Auditorium Portal',
    status: 'ONLINE',
    lastSync: '09:42 AM',
    antennaCount: 8,
    frequencyBand: '865.7 - 867.5 MHz (EPC Gen 2)',
    tagsDetectedToday: 640,
    signalStrength: 100,
    ipAddress: '192.168.10.48'
  }
];

export const INITIAL_ROOM_204_SESSION: ClassroomSession = {
  id: 'SES-204-CN',
  roomNumber: 'Room 204',
  subject: 'Computer Networks (CS301)',
  instructor: 'Prof. K. Venkatesh',
  department: 'Computer Science & Engineering',
  sessionActive: true,
  studentsInside: 42,
  expected: 47,
  entryWindow: '09:00 AM',
  currentTime: '09:42 AM',
  readerStatus: 'ONLINE',
  rfidReaderName: 'Reader 01',
  liveActivity: [
    {
      id: 'act-1',
      timestamp: '09:01 AM',
      studentName: 'Karthik Raja',
      studentId: 'SEC24CSE1004',
      event: 'Student entered',
      rfidSignal: '-54 dBm (Portal Antenna A)'
    },
    {
      id: 'act-2',
      timestamp: '09:03 AM',
      studentName: 'Arun Kumar',
      studentId: 'SEC24CSE1023',
      event: 'Student entered',
      rfidSignal: '-51 dBm (Portal Antenna B)'
    },
    {
      id: 'act-3',
      timestamp: '09:05 AM',
      studentName: 'Priya Sharma',
      studentId: 'SEC24CSE1045',
      event: 'Student entered',
      rfidSignal: '-56 dBm (Portal Antenna A)'
    },
    {
      id: 'act-4',
      timestamp: '09:12 AM',
      studentName: 'Tanvi Joshi',
      studentId: 'SEC24CSE1062',
      event: 'Student entered',
      duration: 'Marked Late (+12m)',
      rfidSignal: '-61 dBm (Portal Antenna A)'
    },
    {
      id: 'act-5',
      timestamp: '09:35 AM',
      studentName: 'Sanjay Dutt V.',
      studentId: 'SEC24CSE1078',
      event: 'Student exited',
      duration: 'Session duration: 34m',
      rfidSignal: '-53 dBm (Portal Antenna C - Exit Vector)'
    }
  ]
};

export const ENROLLED_STUDENTS_LIST: { id: string; name: string; dept: string; tagId: string; attendanceRate: number; status: string }[] = [
  { id: 'SEC24CSE1023', name: 'Arun Kumar', dept: 'CSE', tagId: 'E280-1160-4492-7A01', attendanceRate: 91.6, status: 'Present' },
  { id: 'SEC24CSE1004', name: 'Karthik Raja', dept: 'CSE', tagId: 'E280-1160-4492-1B09', attendanceRate: 94.2, status: 'Present' },
  { id: 'SEC24CSE1045', name: 'Priya Sharma', dept: 'CSE', tagId: 'E280-1160-4492-3C44', attendanceRate: 88.4, status: 'Present' },
  { id: 'SEC24CSE1062', name: 'Tanvi Joshi', dept: 'CSE', tagId: 'E280-1160-4492-9D22', attendanceRate: 85.0, status: 'Late' },
  { id: 'SEC24CSE1078', name: 'Sanjay Dutt V.', dept: 'CSE', tagId: 'E280-1160-4492-5E11', attendanceRate: 79.5, status: 'Present' },
  { id: 'SEC24CSE1089', name: 'Vikas Rao', dept: 'CSE', tagId: 'E280-1160-4492-8F77', attendanceRate: 92.1, status: 'Present' },
  { id: 'SEC24CSE1018', name: 'Ananya Deshmukh', dept: 'CSE', tagId: 'E280-1160-4492-2A88', attendanceRate: 96.0, status: 'Present' },
  { id: 'SEC24CSE1042', name: 'Sneha Reddy', dept: 'CSE', tagId: 'E280-1160-4492-4C33', attendanceRate: 89.2, status: 'Present' },
  { id: 'SEC24CSE1112', name: 'Deepak Nambiar', dept: 'CSE', tagId: 'E280-1160-4492-6D55', attendanceRate: 74.0, status: 'Absent' },
  { id: 'SEC24CSE1150', name: 'Aditya Nair', dept: 'CSE', tagId: 'E280-1160-4492-7E99', attendanceRate: 82.3, status: 'Present' },
  { id: 'SEC24ECE2001', name: 'Megha Varma', dept: 'ECE', tagId: 'E280-1160-4493-1102', attendanceRate: 93.5, status: 'Present' },
  { id: 'SEC24ME3014', name: 'Rahul Chhabra', dept: 'MECH', tagId: 'E280-1160-4494-8841', attendanceRate: 86.7, status: 'Absent' }
];

export const ALL_CLASSROOMS = [
  { id: 'CR-204', room: 'Room 204', dept: 'Computer Science', capacity: 60, currentSubject: 'Computer Networks', reader: 'Reader 01', status: 'ONLINE', inside: 42, expected: 47 },
  { id: 'CR-205', room: 'Room 205', dept: 'Computer Science', capacity: 60, currentSubject: 'Data Structures', reader: 'Reader 02', status: 'ONLINE', inside: 55, expected: 58 },
  { id: 'CR-301', room: 'Room 301', dept: 'Electronics', capacity: 50, currentSubject: 'VLSI Design', reader: 'Reader 03', status: 'OFFLINE', inside: 0, expected: 48 },
  { id: 'CR-305', room: 'Room 305', dept: 'Cyber Security', capacity: 45, currentSubject: 'Cryptography', reader: 'Reader 07', status: 'ONLINE', inside: 39, expected: 42 },
  { id: 'LAB-02', room: 'Lab 2 (Systems)', dept: 'Computer Science', capacity: 40, currentSubject: 'OS Practical', reader: 'Reader 09', status: 'ONLINE', inside: 38, expected: 40 },
  { id: 'LAB-03', room: 'Lab 3 (Databases)', dept: 'Computer Science', capacity: 40, currentSubject: 'SQL Studio', reader: 'Reader 10', status: 'ONLINE', inside: 36, expected: 38 },
];
